services:
  - type: web
    name: greencycle-api
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://greencycle:753159@cluster0.0unqeid.mongodb.net/greencycle?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: greencycle-super-secret-jwt-key-change-in-prod
      - key: JWT_EXPIRE
        value: 30d
      - key: ADMIN_PHONE
        value: "+918309108691"
      - key: ADMIN_PASSWORD
        value: GreenCycle@2024
      - key: BUSINESS_PHONE
        value: "+918309108691"
      - key: BUSINESS_WHATSAPP
        value: "+918309108691"
      - key: BUSINESS_NAME
        value: GreenCycle Premium Scrap Services
